# Generated by Django 4.2.7 on 2026-02-03 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BreederListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('license_number', models.CharField(blank=True, help_text='Breeding license number', max_length=100)),
                ('species_specialization', models.CharField(help_text='e.g., Dogs, Cats, Birds', max_length=100)),
                ('breeds_available', models.TextField(help_text='List of breeds you specialize in')),
                ('location', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(help_text='About your breeding program')),
                ('experience_years', models.PositiveIntegerField(help_text='Years of breeding experience')),
                ('health_testing', models.BooleanField(default=False, help_text='Do you conduct health testing?')),
                ('health_guarantee', models.BooleanField(default=False, help_text='Do you provide health guarantee?')),
                ('certifications', models.TextField(blank=True, help_text='Professional certifications and memberships')),
                ('photo', models.ImageField(blank=True, help_text='Business or facility photo', upload_to='breeders/')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('breeder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeder_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-verification_status', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BreederReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')])),
                ('title', models.CharField(max_length=200)),
                ('review_text', models.TextField()),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('would_recommend', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('breeder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='breeding.breederlisting')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeder_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('breeder', 'reviewer')},
            },
        ),
    ]
