# Generated by Django 4.2.7 on 2026-02-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost in Indian Rupees (₹)', max_digits=8, null=True),
        ),
    ]
