# Generated by Django 4.2.7 on 2026-02-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_healthrecord_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='activity_level',
            field=models.CharField(choices=[('low', 'Low Activity'), ('medium', 'Medium Activity'), ('high', 'High Activity')], default='medium', help_text="Pet's activity level", max_length=10),
        ),
    ]
