# Generated by Django 4.2.7 on 2026-02-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_dietrecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='custom_species',
            field=models.CharField(blank=True, help_text='For species not in the list (admin only)', max_length=100),
        ),
    ]
