# Generated by Django 4.2.7 on 2026-02-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_pet_custom_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='microchip_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
