# Generated by Django 4.2.7 on 2026-02-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostpetreport',
            name='additional_photos',
            field=models.TextField(blank=True, help_text='URLs or descriptions of additional photos'),
        ),
        migrations.AddField(
            model_name='lostpetreport',
            name='age_estimate',
            field=models.CharField(default='unknow', help_text='Approximate age (e.g., 2 years, puppy, senior)', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lostpetreport',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='lostpetreport',
            name='description',
            field=models.TextField(help_text='Detailed description including behavior, distinctive marks, etc.'),
        ),
        migrations.AlterField(
            model_name='lostpetreport',
            name='photo',
            field=models.ImageField(default='unknown', help_text='Upload a clear photo of the pet', upload_to='lost_pets/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lostpetreport',
            name='size',
            field=models.CharField(choices=[('small', 'Small (under 25 lbs)'), ('medium', 'Medium (25-60 lbs)'), ('large', 'Large (60-100 lbs)'), ('extra_large', 'Extra Large (over 100 lbs)')], max_length=15),
        ),
    ]
