# Generated by Django 4.2.7 on 2026-02-03 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_lostpetreport_additional_photos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumreply',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_replies', to='community.forumreply'),
        ),
    ]
