# Generated by Django 4.2.7 on 2026-02-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_forumreply_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostpetreport',
            name='reward_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Reward amount in Indian Rupees (₹)', max_digits=8, null=True),
        ),
    ]
